<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>9.0</LangVersion>
    <AssemblyName>Bootstrap</AssemblyName>
    <RootNamespace>Bootstrap</RootNamespace>
    <Company>东南大学 声绘鹞影实践团</Company>
    <Product>小鹞 WhistleBot</Product>
    <Description>开发人员：Ainepadma</Description>
    <AssemblyTitle>小鹞 WhistleBot</AssemblyTitle>
    <Version>1.2.0</Version>
    <ApplicationIcon>..\..\assets\app.ico</ApplicationIcon>
    <Nullable>disable</Nullable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>
